### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by MegaphoneJon** [mhawksey/CiviService-for-Google-Script#2]
Hi Martin,

This is very cool! I stumbled across this while looking for something unrelated.

I wrote a script for a very similar purpose: https://gist.github.com/MegaphoneJon/b1b344edeba594bbdd0acb0c31f47c6b

Your Google Script is much more robust, but if you're still using this, I wanted to make sure you were aware of the [Form Processor](https://lab.civicrm.org/extensions/form-processor) extension, which I rely on.

While the CiviCRM API by default only allows you to interact with a single entity at a time, Form Processor defines a single endpoint, and provides a GUI that allows you to send the submitted JSON to a variety of APIs, and even transform the data in the process.  E.g. I have a Google Form that creates up to seven contacts, relationships between them, and creates a membership.

When I have time I may try to incorporate some of your tricks, and perhaps implement your library.  Thanks for sharing this!

**Comment by mhawksey** [comment]
Nice! Not actively maintaining this library but thanks for leaving a comment for others looking to handle form responses
